name: analyzer_plugin_toolkit_example
description: Demonstrates the analyzer_plugin_toolkit building blocks.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.11.0

dependencies:
  analyzer: ^14.4.0
  analyzer_plugin_toolkit: ^1.0.0

dev_dependencies:
  arxdeus_lints: ^1.0.0
