#!/usr/bin/env bash
#
# Makes a standalone clone of this repository resolvable, and points its example
# at the working tree.
#
# Two things here only make sense inside the workspace this package is
# developed in:
#
#   * `resolution: workspace` in pubspec.yaml, which needs a workspace root in
#     some parent directory, and
#   * nothing else. The example resolves entirely from pub.dev.
#
# `resolution` does not survive publication either: pub strips it from the
# pubspec it uploads. So the detached tree this produces is close to what a
# consumer gets, which is why CI checks that rather than the workspace.
#
# The override this writes exists for one reason. The example depends on a
# *published* version of this package, which is what makes it a faithful
# demonstration and what earns the pana points. But that means CI would analyse
# the example against the last release rather than the commit under test, and a
# breaking change to the toolkit would sail through green. Redirecting the
# example at the working tree closes that gap.
#
# The file is generated, never committed, and .gitignore keeps it that way.
# Everything else the example needs, arxdeus_lints included, resolves from
# pub.dev exactly as a consumer's project does.
#
# Idempotent, and safe to run in a clone you are working in, though it does edit
# pubspec.yaml: do not commit that.

set -euo pipefail

cd "$(dirname "$0")/../.."

sed -i.bak '/^resolution: workspace$/d' pubspec.yaml && rm -f pubspec.yaml.bak

cat > example/pubspec_overrides.yaml <<'YAML'
# Generated by .github/tool/detach_workspace.sh. Not tracked in git.
#
# Analyses the example against the working tree instead of the last published
# release, so a breaking change cannot pass CI unnoticed.
dependency_overrides:
  analyzer_plugin_toolkit:
    path: ../
YAML

echo "detached: dropped resolution: workspace, pointed the example at the tree"
